/**
 * AUTO-GENERATED by scripts/buildSeedData.mjs — do not edit by hand.
 * Source of truth: wanderwise/src/data.js (the prototype's curated dataset).
 * Shapes match backend spec §2.
 */
module.exports = {
  "cities": [
    {
      "id": "jaipur",
      "name": "Jaipur",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=900&q=70",
      "description": "The Pink City — palaces, bazaars and royal heritage",
      "bestTimeToVisit": "October to March",
      "languages": [
        "Hindi",
        "English"
      ],
      "pricePerDay": {
        "budget": 2500,
        "mid": 6500,
        "luxury": 18000
      },
      "culture": {
        "history": "Founded in 1727 by Maharaja Sawai Jai Singh II, Jaipur was India's first planned city, laid out on a nine-block Vastu grid. Its terracotta-pink wash was painted in 1876 to welcome the Prince of Wales and has stayed ever since. The city remains a living workshop of block printing, blue pottery, kundan jewellery and Kathputli puppetry.",
        "originText": "Founded in 1727 by Maharaja Sawai Jai Singh II, Jaipur was India's first planned city, laid out on a nine-block Vastu grid. Its terracotta-pink wash was painted in 1876 to welcome the Prince of Wales and has stayed ever since. The city remains a living workshop of block printing, blue pottery, kundan jewellery and Kathputli puppetry."
      },
      "delicacies": [
        {
          "dish": "Dal Baati Churma",
          "bestPlace": "Laxmi Misthan Bhandar",
          "note": "Baked wheat balls drowned in ghee, with sweet churma."
        },
        {
          "dish": "Pyaaz Kachori",
          "bestPlace": "Rawat Mishtan Bhandar",
          "note": "Onion-stuffed and fried; eat it hot, standing."
        },
        {
          "dish": "Laal Maas",
          "bestPlace": "Handi Restaurant",
          "note": "Fiery Mathania-chilli mutton curry."
        },
        {
          "dish": "Ghewar",
          "bestPlace": "Sodhani Sweets",
          "note": "Honeycomb disc soaked in syrup — a Teej season sweet."
        }
      ],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 26.9124,
      "lng": 75.7873
    },
    {
      "id": "delhi",
      "name": "Delhi",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=900&q=70",
      "description": "Millennia of empires layered inside one restless capital",
      "bestTimeToVisit": "October to March",
      "languages": [
        "Hindi",
        "English",
        "Punjabi"
      ],
      "pricePerDay": {
        "budget": 2200,
        "mid": 6000,
        "luxury": 16000
      },
      "culture": {
        "history": "Seven historic cities stack beneath modern Delhi, from Tughlaqabad to Shahjahanabad. Mughal domes, colonial boulevards and Partition-era refugee colonies sit within a few kilometres of each other, producing a food and music culture that is unapologetically mixed.",
        "originText": "Seven historic cities stack beneath modern Delhi, from Tughlaqabad to Shahjahanabad. Mughal domes, colonial boulevards and Partition-era refugee colonies sit within a few kilometres of each other, producing a food and music culture that is unapologetically mixed."
      },
      "delicacies": [
        {
          "dish": "Butter Chicken",
          "bestPlace": "Moti Mahal, Daryaganj",
          "note": "Invented here in the 1940s."
        },
        {
          "dish": "Chole Bhature",
          "bestPlace": "Sita Ram Diwan Chand",
          "note": "The Paharganj benchmark."
        },
        {
          "dish": "Nihari",
          "bestPlace": "Karim's",
          "note": "Slow-cooked overnight; go before 10am."
        },
        {
          "dish": "Daulat ki Chaat",
          "bestPlace": "Chandni Chowk, winter only",
          "note": "Milk foam set under dew; sold before noon."
        }
      ],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 28.6139,
      "lng": 77.209
    },
    {
      "id": "mumbai",
      "name": "Mumbai",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?auto=format&fit=crop&w=900&q=70",
      "description": "Seven islands turned into India's restless dream factory",
      "bestTimeToVisit": "November to February",
      "languages": [
        "Marathi",
        "Hindi",
        "English"
      ],
      "pricePerDay": {
        "budget": 2800,
        "mid": 7500,
        "luxury": 22000
      },
      "culture": {
        "history": "From Koli fishing villages to Art Deco Marine Drive to Bollywood, Mumbai runs on migration and hustle. Its Gothic-Revival and Deco ensembles are UNESCO-listed.",
        "originText": "From Koli fishing villages to Art Deco Marine Drive to Bollywood, Mumbai runs on migration and hustle. Its Gothic-Revival and Deco ensembles are UNESCO-listed."
      },
      "delicacies": [],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 19.076,
      "lng": 72.8777
    },
    {
      "id": "goa",
      "name": "Goa",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=900&q=70",
      "description": "Beaches, Portuguese churches and long lazy lunches",
      "bestTimeToVisit": "November to February",
      "languages": [
        "Konkani",
        "English",
        "Hindi"
      ],
      "pricePerDay": {
        "budget": 1800,
        "mid": 5500,
        "luxury": 20000
      },
      "culture": {
        "history": "451 years of Portuguese rule left baroque churches, azulejo tiles, feni distilling and a Indo-Latin cuisine found nowhere else in India.",
        "originText": "451 years of Portuguese rule left baroque churches, azulejo tiles, feni distilling and a Indo-Latin cuisine found nowhere else in India."
      },
      "delicacies": [],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 15.2993,
      "lng": 74.124
    },
    {
      "id": "udaipur",
      "name": "Udaipur",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1609920658906-8223bd289001?auto=format&fit=crop&w=900&q=70",
      "description": "The City of Lakes — marble palaces on still water",
      "bestTimeToVisit": "September to March",
      "languages": [
        "Hindi",
        "Mewari",
        "English"
      ],
      "pricePerDay": {
        "budget": 2400,
        "mid": 7000,
        "luxury": 25000
      },
      "culture": {
        "history": "Capital of Mewar since 1559 and home to the world's longest-serving royal dynasty. Miniature painting in the Mewar school still thrives in the old city lanes.",
        "originText": "Capital of Mewar since 1559 and home to the world's longest-serving royal dynasty. Miniature painting in the Mewar school still thrives in the old city lanes."
      },
      "delicacies": [],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 24.5854,
      "lng": 73.7125
    },
    {
      "id": "varanasi",
      "name": "Varanasi",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=900&q=70",
      "description": "The oldest living city — ghats, aarti and Ganga at dawn",
      "bestTimeToVisit": "October to March",
      "languages": [
        "Hindi",
        "Bhojpuri"
      ],
      "pricePerDay": {
        "budget": 1600,
        "mid": 4500,
        "luxury": 14000
      },
      "culture": {
        "history": "Continuously inhabited for over 3,000 years, Kashi is the seat of Banarasi silk weaving, Hindustani classical music and the nightly Ganga Aarti at Dashashwamedh Ghat.",
        "originText": "Continuously inhabited for over 3,000 years, Kashi is the seat of Banarasi silk weaving, Hindustani classical music and the nightly Ganga Aarti at Dashashwamedh Ghat."
      },
      "delicacies": [],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 25.3176,
      "lng": 82.9739
    },
    {
      "id": "agra",
      "name": "Agra",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=900&q=70",
      "description": "The Taj, a red fort, and Mughal marble at its peak",
      "bestTimeToVisit": "October to March",
      "languages": [
        "Hindi",
        "Urdu",
        "English"
      ],
      "pricePerDay": {
        "budget": 1600,
        "mid": 4800,
        "luxury": 15000
      },
      "culture": {
        "history": "Mughal capital under Akbar, Jahangir and Shah Jahan. Its pietra dura marble inlay workshops are staffed by descendants of the Taj's original artisans.",
        "originText": "Mughal capital under Akbar, Jahangir and Shah Jahan. Its pietra dura marble inlay workshops are staffed by descendants of the Taj's original artisans."
      },
      "delicacies": [
        {
          "dish": "Petha",
          "bestPlace": "Panchhi Petha Store",
          "note": "Ash-gourd candy — try the kesar and paan versions."
        },
        {
          "dish": "Mughlai Thali",
          "bestPlace": "Pinch of Spice",
          "note": "Korma, biryani and sheermal in one tray."
        },
        {
          "dish": "Bedai & Jalebi",
          "bestPlace": "Deviram Sweets",
          "note": "The classic Agra breakfast."
        }
      ],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 27.1767,
      "lng": 78.0081
    },
    {
      "id": "kolkata",
      "name": "Kolkata",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=900&q=70",
      "description": "Coffee-house debates, colonial bones and Durga Puja",
      "bestTimeToVisit": "October to March",
      "languages": [
        "Bengali",
        "Hindi",
        "English"
      ],
      "pricePerDay": {
        "budget": 1800,
        "mid": 5000,
        "luxury": 14000
      },
      "culture": {
        "history": "Capital of British India until 1911 and the engine of the Bengal Renaissance — Tagore, Ray, adda culture and the UNESCO-listed Durga Puja.",
        "originText": "Capital of British India until 1911 and the engine of the Bengal Renaissance — Tagore, Ray, adda culture and the UNESCO-listed Durga Puja."
      },
      "delicacies": [],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 22.5726,
      "lng": 88.3639
    },
    {
      "id": "kerala",
      "name": "Kerala",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=900&q=70",
      "description": "Backwaters, houseboats and coconut-green calm",
      "bestTimeToVisit": "September to March",
      "languages": [
        "Malayalam",
        "English"
      ],
      "pricePerDay": {
        "budget": 2200,
        "mid": 6000,
        "luxury": 19000
      },
      "culture": {
        "history": "Spice-trade coastline with 2,000 years of Roman, Arab and Chinese contact. Kathakali, Theyyam and Ayurveda are living traditions here, not performances.",
        "originText": "Spice-trade coastline with 2,000 years of Roman, Arab and Chinese contact. Kathakali, Theyyam and Ayurveda are living traditions here, not performances."
      },
      "delicacies": [],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 9.4981,
      "lng": 76.3388
    },
    {
      "id": "kashmir",
      "name": "Kashmir",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1566323834-3a5b1e5c8b46?auto=format&fit=crop&w=900&q=70",
      "description": "Shikaras, saffron fields and Himalayan meadows",
      "bestTimeToVisit": "April to October",
      "languages": [
        "Kashmiri",
        "Urdu",
        "English"
      ],
      "pricePerDay": {
        "budget": 2600,
        "mid": 7000,
        "luxury": 21000
      },
      "culture": {
        "history": "Mughal pleasure gardens, Sufi shrines and a craft economy of pashmina, papier-mâché and walnut wood carving.",
        "originText": "Mughal pleasure gardens, Sufi shrines and a craft economy of pashmina, papier-mâché and walnut wood carving."
      },
      "delicacies": [],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 34.0837,
      "lng": 74.7973
    },
    {
      "id": "chennai",
      "name": "Chennai",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=900&q=70",
      "description": "Carnatic music, filter coffee and a very long beach",
      "bestTimeToVisit": "November to February",
      "languages": [
        "Tamil",
        "English"
      ],
      "pricePerDay": {
        "budget": 1800,
        "mid": 5000,
        "luxury": 15000
      },
      "culture": {
        "history": "Home of Bharatanatyam and the December Margazhi music season, with Dravidian temple architecture at nearby Mahabalipuram.",
        "originText": "Home of Bharatanatyam and the December Margazhi music season, with Dravidian temple architecture at nearby Mahabalipuram."
      },
      "delicacies": [],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 13.0827,
      "lng": 80.2707
    },
    {
      "id": "mysuru",
      "name": "Mysuru",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1600100397608-f010d1e63d43?auto=format&fit=crop&w=900&q=70",
      "description": "Palace lights, sandalwood and silk",
      "bestTimeToVisit": "October to February",
      "languages": [
        "Kannada",
        "English"
      ],
      "pricePerDay": {
        "budget": 1700,
        "mid": 4800,
        "luxury": 14000
      },
      "culture": {
        "history": "Seat of the Wadiyar dynasty. Dasara here is a ten-day state festival with a caparisoned-elephant procession.",
        "originText": "Seat of the Wadiyar dynasty. Dasara here is a ten-day state festival with a caparisoned-elephant procession."
      },
      "delicacies": [],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 12.2958,
      "lng": 76.6394
    },
    {
      "id": "pushkar",
      "name": "Pushkar",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=900&q=70",
      "description": "A holy lake, 500 temples and the camel fair",
      "bestTimeToVisit": "October to March",
      "languages": [
        "Hindi",
        "Marwari"
      ],
      "pricePerDay": {
        "budget": 1400,
        "mid": 4000,
        "luxury": 12000
      },
      "culture": {
        "history": "One of the only Brahma temples on earth sits by a lake said to have formed where a lotus fell. The November camel fair draws 200,000 people.",
        "originText": "One of the only Brahma temples on earth sits by a lake said to have formed where a lotus fell. The November camel fair draws 200,000 people."
      },
      "delicacies": [],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 26.4899,
      "lng": 74.5511
    },
    {
      "id": "ahmedabad",
      "name": "Ahmedabad",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=900&q=70",
      "description": "India's first UNESCO World Heritage City",
      "bestTimeToVisit": "November to February",
      "languages": [
        "Gujarati",
        "Hindi",
        "English"
      ],
      "pricePerDay": {
        "budget": 1600,
        "mid": 4500,
        "luxury": 13000
      },
      "culture": {
        "history": "Pol houses, Indo-Islamic stone jaalis, Gandhi's Sabarmati Ashram and a textile industry that earned it \"Manchester of the East\".",
        "originText": "Pol houses, Indo-Islamic stone jaalis, Gandhi's Sabarmati Ashram and a textile industry that earned it \"Manchester of the East\"."
      },
      "delicacies": [],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 23.0225,
      "lng": 72.5714
    },
    {
      "id": "puri",
      "name": "Jagannath Puri",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=900&q=70",
      "description": "Temple town on the Bay of Bengal",
      "bestTimeToVisit": "October to February",
      "languages": [
        "Odia",
        "Hindi"
      ],
      "pricePerDay": {
        "budget": 1300,
        "mid": 3800,
        "luxury": 11000
      },
      "culture": {
        "history": "The 12th-century Jagannath Temple and its Rath Yatra — the chariot festival that gave English the word \"juggernaut\".",
        "originText": "The 12th-century Jagannath Temple and its Rath Yatra — the chariot festival that gave English the word \"juggernaut\"."
      },
      "delicacies": [],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 19.8135,
      "lng": 85.8312
    },
    {
      "id": "pune",
      "name": "Pune",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=900&q=70",
      "description": "Maratha history with a young, green campus feel",
      "bestTimeToVisit": "October to February",
      "languages": [
        "Marathi",
        "Hindi",
        "English"
      ],
      "pricePerDay": {
        "budget": 1700,
        "mid": 4800,
        "luxury": 13000
      },
      "culture": {
        "history": "Peshwa capital of the Maratha Empire and today a university and tech city with a strong theatre and food scene.",
        "originText": "Peshwa capital of the Maratha Empire and today a university and tech city with a strong theatre and food scene."
      },
      "delicacies": [],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 18.5204,
      "lng": 73.8567
    },
    {
      "id": "hyderabad",
      "name": "Hyderabad",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1600100397608-f010d1e63d43?auto=format&fit=crop&w=900&q=70",
      "description": "Nizami grandeur, biryani and pearls",
      "bestTimeToVisit": "October to February",
      "languages": [
        "Telugu",
        "Urdu",
        "English"
      ],
      "pricePerDay": {
        "budget": 1800,
        "mid": 5200,
        "luxury": 16000
      },
      "culture": {
        "history": "Qutb Shahi and Asaf Jahi rule produced the Charminar, Golconda's diamonds, Deccani miniature painting and Hyderabadi dum biryani.",
        "originText": "Qutb Shahi and Asaf Jahi rule produced the Charminar, Golconda's diamonds, Deccani miniature painting and Hyderabadi dum biryani."
      },
      "delicacies": [],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 17.385,
      "lng": 78.4867
    },
    {
      "id": "darjeeling",
      "name": "Darjeeling",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=900&q=70",
      "description": "Tea gardens, toy trains and Kanchenjunga at sunrise",
      "bestTimeToVisit": "March to May, October to November",
      "languages": [
        "Nepali",
        "Bengali",
        "English"
      ],
      "pricePerDay": {
        "budget": 1900,
        "mid": 5000,
        "luxury": 15000
      },
      "culture": {
        "history": "A Raj-era hill station whose Himalayan Railway is a UNESCO site and whose first-flush tea is auctioned worldwide.",
        "originText": "A Raj-era hill station whose Himalayan Railway is a UNESCO site and whose first-flush tea is auctioned worldwide."
      },
      "delicacies": [],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 27.036,
      "lng": 88.2627
    },
    {
      "id": "shimla",
      "name": "Shimla",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=900&q=70",
      "description": "The summer capital of the Raj on a pine ridge",
      "bestTimeToVisit": "March to June, December to January",
      "languages": [
        "Hindi",
        "Pahari",
        "English"
      ],
      "pricePerDay": {
        "budget": 1800,
        "mid": 5000,
        "luxury": 15000
      },
      "culture": {
        "history": "Mock-Tudor architecture on the Mall Road, the Kalka–Shimla toy train and Himachali temple woodcraft.",
        "originText": "Mock-Tudor architecture on the Mall Road, the Kalka–Shimla toy train and Himachali temple woodcraft."
      },
      "delicacies": [],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 31.1048,
      "lng": 77.1734
    },
    {
      "id": "leh",
      "name": "Leh (Ladakh)",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=900&q=70",
      "description": "High-desert monasteries above 3,500 m",
      "bestTimeToVisit": "June to September",
      "languages": [
        "Ladakhi",
        "Hindi",
        "English"
      ],
      "pricePerDay": {
        "budget": 2400,
        "mid": 6500,
        "luxury": 20000
      },
      "culture": {
        "history": "Tibetan Buddhist gompas, Hemis festival masked dance, and the trans-Himalayan trade route that ran to Yarkand.",
        "originText": "Tibetan Buddhist gompas, Hemis festival masked dance, and the trans-Himalayan trade route that ran to Yarkand."
      },
      "delicacies": [],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 34.1526,
      "lng": 77.5771
    },
    {
      "id": "kochi",
      "name": "Kochi (Alleppey)",
      "country": "India",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1593693411515-c20261bcad6e?auto=format&fit=crop&w=900&q=70",
      "description": "Chinese nets, spice godowns and canal towns",
      "bestTimeToVisit": "October to March",
      "languages": [
        "Malayalam",
        "English"
      ],
      "pricePerDay": {
        "budget": 2000,
        "mid": 5500,
        "luxury": 17000
      },
      "culture": {
        "history": "Fort Kochi layers Portuguese, Dutch, Jewish and British history into a few walkable blocks; Alleppey adds the backwater houseboats.",
        "originText": "Fort Kochi layers Portuguese, Dutch, Jewish and British history into a few walkable blocks; Alleppey adds the backwater houseboats."
      },
      "delicacies": [],
      "isInternational": false,
      "isComingSoon": false,
      "lat": 9.9312,
      "lng": 76.2673
    },
    {
      "id": "bangkok",
      "name": "Bangkok",
      "country": "Thailand",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=900&q=70",
      "description": "Golden temples, canal markets and street food till 3am",
      "bestTimeToVisit": "November to February",
      "languages": [
        "Thai",
        "English"
      ],
      "pricePerDay": {
        "budget": 1200,
        "mid": 3200,
        "luxury": 9000
      },
      "culture": {
        "history": "Rattanakosin-era temples and the Chao Phraya's klongs sit under a skyline of BTS lines and rooftop bars.",
        "originText": "Rattanakosin-era temples and the Chao Phraya's klongs sit under a skyline of BTS lines and rooftop bars."
      },
      "delicacies": [],
      "isInternational": true,
      "isComingSoon": false,
      "lat": 13.7563,
      "lng": 100.5018
    },
    {
      "id": "hongkong",
      "name": "Hong Kong",
      "country": "China",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1536599018102-9f803c140fc1?auto=format&fit=crop&w=900&q=70",
      "description": "Neon harbour city where dim sum meets skyscrapers",
      "bestTimeToVisit": "October to December",
      "languages": [
        "Cantonese",
        "English"
      ],
      "pricePerDay": {
        "budget": 2600,
        "mid": 7000,
        "luxury": 23400
      },
      "culture": {
        "history": "A treaty port turned finance capital, with tea houses, temple markets and 200 outlying islands.",
        "originText": "A treaty port turned finance capital, with tea houses, temple markets and 200 outlying islands."
      },
      "delicacies": [],
      "isInternational": true,
      "isComingSoon": false,
      "lat": 22.3193,
      "lng": 114.1694
    },
    {
      "id": "london",
      "name": "London",
      "country": "UK",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=900&q=70",
      "description": "Museums, markets and two thousand years of layers",
      "bestTimeToVisit": "May to September",
      "languages": [
        "English"
      ],
      "pricePerDay": {
        "budget": 6000,
        "mid": 14000,
        "luxury": 40000
      },
      "culture": {
        "history": "Roman Londinium to the Southbank — free national museums, West End theatre and a genuinely global food map.",
        "originText": "Roman Londinium to the Southbank — free national museums, West End theatre and a genuinely global food map."
      },
      "delicacies": [],
      "isInternational": true,
      "isComingSoon": false,
      "lat": 51.5074,
      "lng": -0.1278
    },
    {
      "id": "istanbul",
      "name": "Istanbul",
      "country": "Turkey",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=900&q=70",
      "description": "Two continents, one skyline of domes and minarets",
      "bestTimeToVisit": "April to June, September to November",
      "languages": [
        "Turkish",
        "English"
      ],
      "pricePerDay": {
        "budget": 2200,
        "mid": 6000,
        "luxury": 18000
      },
      "culture": {
        "history": "Byzantine Constantinople and Ottoman Istanbul overlap at Hagia Sophia, the Grand Bazaar and the Bosphorus ferries.",
        "originText": "Byzantine Constantinople and Ottoman Istanbul overlap at Hagia Sophia, the Grand Bazaar and the Bosphorus ferries."
      },
      "delicacies": [],
      "isInternational": true,
      "isComingSoon": false,
      "lat": 41.0082,
      "lng": 28.9784
    },
    {
      "id": "dubai",
      "name": "Dubai",
      "country": "UAE",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=900&q=70",
      "description": "Desert futurism, souks and record-breaking towers",
      "bestTimeToVisit": "November to March",
      "languages": [
        "Arabic",
        "English"
      ],
      "pricePerDay": {
        "budget": 4000,
        "mid": 11000,
        "luxury": 35000
      },
      "culture": {
        "history": "A pearling creek town that became a global hub in fifty years; Al Fahidi's wind towers still show the old city.",
        "originText": "A pearling creek town that became a global hub in fifty years; Al Fahidi's wind towers still show the old city."
      },
      "delicacies": [],
      "isInternational": true,
      "isComingSoon": false,
      "lat": 25.2048,
      "lng": 55.2708
    },
    {
      "id": "makkah",
      "name": "Makkah",
      "country": "Saudi Arabia",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?auto=format&fit=crop&w=900&q=70",
      "description": "The holiest city in Islam, open year-round for Umrah",
      "bestTimeToVisit": "November to February",
      "languages": [
        "Arabic",
        "Urdu",
        "English"
      ],
      "pricePerDay": {
        "budget": 3500,
        "mid": 9000,
        "luxury": 28000
      },
      "culture": {
        "history": "The Masjid al-Haram surrounds the Kaaba; the Hajj draws over two million pilgrims each year.",
        "originText": "The Masjid al-Haram surrounds the Kaaba; the Hajj draws over two million pilgrims each year."
      },
      "delicacies": [],
      "isInternational": true,
      "isComingSoon": false,
      "lat": 21.3891,
      "lng": 39.8579
    },
    {
      "id": "antalya",
      "name": "Antalya",
      "country": "Turkey",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1602898568500-2e0b1f8b1a4f?auto=format&fit=crop&w=900&q=70",
      "description": "Turquoise coast, Roman ruins and old-town harbours",
      "bestTimeToVisit": "April to October",
      "languages": [
        "Turkish",
        "English"
      ],
      "pricePerDay": {
        "budget": 2000,
        "mid": 5500,
        "luxury": 16000
      },
      "culture": {
        "history": "Kaleiçi's Ottoman houses sit above a Roman harbour, with Lycian and Pamphylian ruins along the coast.",
        "originText": "Kaleiçi's Ottoman houses sit above a Roman harbour, with Lycian and Pamphylian ruins along the coast."
      },
      "delicacies": [],
      "isInternational": true,
      "isComingSoon": false,
      "lat": 36.8969,
      "lng": 30.7133
    },
    {
      "id": "paris",
      "name": "Paris",
      "country": "France",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=900&q=70",
      "description": "Boulevards, brasseries and the world's best museums",
      "bestTimeToVisit": "April to June, September to October",
      "languages": [
        "French",
        "English"
      ],
      "pricePerDay": {
        "budget": 5500,
        "mid": 13000,
        "luxury": 38000
      },
      "culture": {
        "history": "Haussmann's boulevards, the Left Bank's cafés and a museum density unmatched anywhere.",
        "originText": "Haussmann's boulevards, the Left Bank's cafés and a museum density unmatched anywhere."
      },
      "delicacies": [],
      "isInternational": true,
      "isComingSoon": false,
      "lat": 48.8566,
      "lng": 2.3522
    },
    {
      "id": "kl",
      "name": "Kuala Lumpur",
      "country": "Malaysia",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?auto=format&fit=crop&w=900&q=70",
      "description": "Towers, temples and a three-cuisine food scene",
      "bestTimeToVisit": "May to July, December to February",
      "languages": [
        "Malay",
        "English"
      ],
      "pricePerDay": {
        "budget": 1500,
        "mid": 4000,
        "luxury": 12000
      },
      "culture": {
        "history": "A tin-mining confluence town that grew into a Malay-Chinese-Indian capital, with Batu Caves on its edge.",
        "originText": "A tin-mining confluence town that grew into a Malay-Chinese-Indian capital, with Batu Caves on its edge."
      },
      "delicacies": [],
      "isInternational": true,
      "isComingSoon": false,
      "lat": 3.139,
      "lng": 101.6869
    },
    {
      "id": "la",
      "name": "Los Angeles",
      "country": "USA",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1580655653885-65763b2597d0?auto=format&fit=crop&w=900&q=70",
      "description": "Sunset boulevards and studio backlots",
      "bestTimeToVisit": "March to May",
      "languages": [
        "English"
      ],
      "pricePerDay": {
        "budget": 7000,
        "mid": 16000,
        "luxury": 45000
      },
      "culture": {
        "history": "",
        "originText": ""
      },
      "delicacies": [],
      "isInternational": true,
      "isComingSoon": true,
      "lat": 34.0522,
      "lng": -118.2437
    },
    {
      "id": "nyc",
      "name": "New York City",
      "country": "USA",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=900&q=70",
      "description": "Five boroughs that never stop",
      "bestTimeToVisit": "April to June",
      "languages": [
        "English"
      ],
      "pricePerDay": {
        "budget": 8000,
        "mid": 18000,
        "luxury": 50000
      },
      "culture": {
        "history": "",
        "originText": ""
      },
      "delicacies": [],
      "isInternational": true,
      "isComingSoon": true,
      "lat": 40.7128,
      "lng": -74.006
    },
    {
      "id": "melbourne",
      "name": "Melbourne",
      "country": "Australia",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1514395462725-fb4566210144?auto=format&fit=crop&w=900&q=70",
      "description": "Laneway coffee and street art",
      "bestTimeToVisit": "March to May",
      "languages": [
        "English"
      ],
      "pricePerDay": {
        "budget": 5000,
        "mid": 12000,
        "luxury": 32000
      },
      "culture": {
        "history": "",
        "originText": ""
      },
      "delicacies": [],
      "isInternational": true,
      "isComingSoon": true,
      "lat": -37.8136,
      "lng": 144.9631
    },
    {
      "id": "tokyo",
      "name": "Tokyo",
      "country": "Japan",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=900&q=70",
      "description": "Precision, neon and 200,000 restaurants",
      "bestTimeToVisit": "March to May",
      "languages": [
        "Japanese"
      ],
      "pricePerDay": {
        "budget": 8000,
        "mid": 18000,
        "luxury": 48000
      },
      "culture": {
        "history": "",
        "originText": ""
      },
      "delicacies": [],
      "isInternational": true,
      "isComingSoon": true,
      "lat": 35.6762,
      "lng": 139.6503
    },
    {
      "id": "toronto",
      "name": "Toronto",
      "country": "Canada",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1517935706615-2717063c2225?auto=format&fit=crop&w=900&q=70",
      "description": "Lakeside and genuinely multicultural",
      "bestTimeToVisit": "May to September",
      "languages": [
        "English",
        "French"
      ],
      "pricePerDay": {
        "budget": 5500,
        "mid": 13000,
        "luxury": 34000
      },
      "culture": {
        "history": "",
        "originText": ""
      },
      "delicacies": [],
      "isInternational": true,
      "isComingSoon": true,
      "lat": 43.6532,
      "lng": -79.3832
    },
    {
      "id": "sydney",
      "name": "Sydney",
      "country": "Australia",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=900&q=70",
      "description": "Harbour, headlands and surf beaches",
      "bestTimeToVisit": "September to November",
      "languages": [
        "English"
      ],
      "pricePerDay": {
        "budget": 5500,
        "mid": 13000,
        "luxury": 36000
      },
      "culture": {
        "history": "",
        "originText": ""
      },
      "delicacies": [],
      "isInternational": true,
      "isComingSoon": true,
      "lat": -33.8688,
      "lng": 151.2093
    },
    {
      "id": "chicago",
      "name": "Chicago",
      "country": "USA",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1494522855154-9297ac14b55f?auto=format&fit=crop&w=900&q=70",
      "description": "Architecture, blues and deep dish",
      "bestTimeToVisit": "June to September",
      "languages": [
        "English"
      ],
      "pricePerDay": {
        "budget": 6000,
        "mid": 14000,
        "luxury": 38000
      },
      "culture": {
        "history": "",
        "originText": ""
      },
      "delicacies": [],
      "isInternational": true,
      "isComingSoon": true,
      "lat": 41.8781,
      "lng": -87.6298
    },
    {
      "id": "birmingham",
      "name": "Birmingham",
      "country": "UK",
      "tags": [],
      "heroImageUrl": "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=900&q=70",
      "description": "Canals, curry houses and Peaky lore",
      "bestTimeToVisit": "May to September",
      "languages": [
        "English"
      ],
      "pricePerDay": {
        "budget": 4500,
        "mid": 10000,
        "luxury": 26000
      },
      "culture": {
        "history": "",
        "originText": ""
      },
      "delicacies": [],
      "isInternational": true,
      "isComingSoon": true,
      "lat": 52.4862,
      "lng": -1.8904
    }
  ],
  "curatedTours": [
    {
      "id": "golden-triangle",
      "name": "Golden Triangle",
      "region": "North India",
      "cityIds": [
        "delhi",
        "agra",
        "jaipur"
      ],
      "durationDays": 5,
      "coverImageUrl": "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=900&q=70"
    },
    {
      "id": "rajasthan-royals",
      "name": "Rajasthan Royals",
      "region": "North India",
      "cityIds": [
        "jaipur",
        "udaipur",
        "pushkar"
      ],
      "durationDays": 5,
      "coverImageUrl": "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=900&q=70"
    },
    {
      "id": "spiritual-north",
      "name": "Spiritual North",
      "region": "North India",
      "cityIds": [
        "delhi",
        "varanasi",
        "kashmir"
      ],
      "durationDays": 7,
      "coverImageUrl": "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=900&q=70"
    },
    {
      "id": "beaches-backwaters",
      "name": "Beaches & Backwaters",
      "region": "South & West",
      "cityIds": [
        "kerala",
        "goa"
      ],
      "durationDays": 6,
      "coverImageUrl": "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=900&q=70"
    },
    {
      "id": "hills-nature",
      "name": "Hill Stations & Nature",
      "region": "Himalayas",
      "cityIds": [
        "kashmir",
        "shimla",
        "leh",
        "darjeeling"
      ],
      "durationDays": 10,
      "coverImageUrl": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=900&q=70"
    }
  ],
  "pois": [
    {
      "id": "poi_jaipur_amber-fort",
      "cityId": "jaipur",
      "name": "Amber Fort",
      "category": "Heritage",
      "description": "Hilltop sandstone & marble fort with Sheesh Mahal mirror palace.",
      "price": 600,
      "rating": 4.7,
      "imageUrl": null,
      "lat": 26.9855,
      "lng": 75.8513
    },
    {
      "id": "poi_jaipur_hawa-mahal",
      "cityId": "jaipur",
      "name": "Hawa Mahal",
      "category": "Heritage",
      "description": "The 'Palace of Winds' — 953 tiny windows in a honeycomb facade.",
      "price": 200,
      "rating": 4.5,
      "imageUrl": null,
      "lat": 26.9239,
      "lng": 75.8267
    },
    {
      "id": "poi_jaipur_city-palace",
      "cityId": "jaipur",
      "name": "City Palace",
      "category": "Heritage",
      "description": "Still-royal residence with courtyards, textiles and armoury museums.",
      "price": 700,
      "rating": 4.6,
      "imageUrl": null,
      "lat": 26.9255,
      "lng": 75.8236
    },
    {
      "id": "poi_jaipur_jantar-mantar",
      "cityId": "jaipur",
      "name": "Jantar Mantar",
      "category": "Heritage",
      "description": "UNESCO observatory with the world's largest stone sundial.",
      "price": 200,
      "rating": 4.4,
      "imageUrl": null,
      "lat": 26.9247,
      "lng": 75.8246
    },
    {
      "id": "poi_jaipur_johari-bazaar",
      "cityId": "jaipur",
      "name": "Johari Bazaar",
      "category": "Market",
      "description": "Gems, kundan jewellery and traditional Rajasthani textiles.",
      "price": 0,
      "rating": 4.3,
      "imageUrl": null,
      "lat": 26.9196,
      "lng": 75.8253
    },
    {
      "id": "poi_jaipur_nahargarh-fort",
      "cityId": "jaipur",
      "name": "Nahargarh Fort",
      "category": "Viewpoint",
      "description": "Sunset over the whole pink grid from the Aravalli ridge.",
      "price": 200,
      "rating": 4.6,
      "imageUrl": null,
      "lat": 26.9374,
      "lng": 75.8153
    },
    {
      "id": "poi_jaipur_chokhi-dhani",
      "cityId": "jaipur",
      "name": "Chokhi Dhani",
      "category": "Experience",
      "description": "Village-themed evening of folk dance, puppets and thali dinner.",
      "price": 1100,
      "rating": 4.2,
      "imageUrl": null,
      "lat": 26.7583,
      "lng": 75.8394
    },
    {
      "id": "poi_jaipur_panna-meena-ka-kund",
      "cityId": "jaipur",
      "name": "Panna Meena ka Kund",
      "category": "Heritage",
      "description": "Symmetrical 16th-century stepwell near Amber.",
      "price": 0,
      "rating": 4.5,
      "imageUrl": null,
      "lat": 26.9885,
      "lng": 75.8494
    },
    {
      "id": "poi_delhi_red-fort",
      "cityId": "delhi",
      "name": "Red Fort",
      "category": "Heritage",
      "description": "Shah Jahan's walled palace-city in Mughal red sandstone.",
      "price": 550,
      "rating": 4.5,
      "imageUrl": null,
      "lat": 28.6562,
      "lng": 77.241
    },
    {
      "id": "poi_delhi_qutub-minar",
      "cityId": "delhi",
      "name": "Qutub Minar",
      "category": "Heritage",
      "description": "73 m victory tower from 1193 and India's first mosque complex.",
      "price": 550,
      "rating": 4.6,
      "imageUrl": null,
      "lat": 28.5245,
      "lng": 77.1855
    },
    {
      "id": "poi_delhi_humayuns-tomb",
      "cityId": "delhi",
      "name": "Humayun's Tomb",
      "category": "Heritage",
      "description": "The garden tomb that became the blueprint for the Taj Mahal.",
      "price": 550,
      "rating": 4.7,
      "imageUrl": null,
      "lat": 28.5933,
      "lng": 77.2507
    },
    {
      "id": "poi_delhi_india-gate",
      "cityId": "delhi",
      "name": "India Gate",
      "category": "Monument",
      "description": "War memorial arch anchoring the Kartavya Path lawns.",
      "price": 0,
      "rating": 4.6,
      "imageUrl": null,
      "lat": 28.6129,
      "lng": 77.2295
    },
    {
      "id": "poi_delhi_lotus-temple",
      "cityId": "delhi",
      "name": "Lotus Temple",
      "category": "Spiritual",
      "description": "Bahá'í house of worship shaped as a 27-petal marble lotus.",
      "price": 0,
      "rating": 4.5,
      "imageUrl": null,
      "lat": 28.5535,
      "lng": 77.2588
    },
    {
      "id": "poi_delhi_jama-masjid",
      "cityId": "delhi",
      "name": "Jama Masjid",
      "category": "Spiritual",
      "description": "India's largest mosque, overlooking Chandni Chowk.",
      "price": 0,
      "rating": 4.5,
      "imageUrl": null,
      "lat": 28.6507,
      "lng": 77.2334
    },
    {
      "id": "poi_delhi_hauz-khas-village",
      "cityId": "delhi",
      "name": "Hauz Khas Village",
      "category": "Experience",
      "description": "Medieval reservoir ruins ringed by bars and design shops.",
      "price": 0,
      "rating": 4.2,
      "imageUrl": null,
      "lat": 28.5535,
      "lng": 77.1943
    },
    {
      "id": "poi_delhi_akshardham",
      "cityId": "delhi",
      "name": "Akshardham",
      "category": "Spiritual",
      "description": "Vast carved-stone temple complex with an evening water show.",
      "price": 170,
      "rating": 4.7,
      "imageUrl": null,
      "lat": 28.6127,
      "lng": 77.2773
    },
    {
      "id": "poi_agra_taj-mahal",
      "cityId": "agra",
      "name": "Taj Mahal",
      "category": "Heritage",
      "description": "The marble mausoleum Shah Jahan built for Mumtaz Mahal.",
      "price": 1100,
      "rating": 4.9,
      "imageUrl": null,
      "lat": 27.1751,
      "lng": 78.0421
    },
    {
      "id": "poi_agra_agra-fort",
      "cityId": "agra",
      "name": "Agra Fort",
      "category": "Heritage",
      "description": "Red sandstone fortress where Shah Jahan was imprisoned in view of the Taj.",
      "price": 650,
      "rating": 4.6,
      "imageUrl": null,
      "lat": 27.1795,
      "lng": 78.0211
    },
    {
      "id": "poi_agra_mehtab-bagh",
      "cityId": "agra",
      "name": "Mehtab Bagh",
      "category": "Viewpoint",
      "description": "Riverside garden with the classic sunset Taj view.",
      "price": 300,
      "rating": 4.4,
      "imageUrl": null,
      "lat": 27.1799,
      "lng": 78.0421
    },
    {
      "id": "poi_agra_fatehpur-sikri",
      "cityId": "agra",
      "name": "Fatehpur Sikri",
      "category": "Heritage",
      "description": "Akbar's abandoned capital, 40 km out — Buland Darwaza and all.",
      "price": 610,
      "rating": 4.5,
      "imageUrl": null,
      "lat": 27.0937,
      "lng": 77.6679
    },
    {
      "id": "poi_agra_itmad-ud-daulah",
      "cityId": "agra",
      "name": "Itmad-ud-Daulah",
      "category": "Heritage",
      "description": "The 'Baby Taj' — first Mughal tomb in white marble inlay.",
      "price": 310,
      "rating": 4.4,
      "imageUrl": null,
      "lat": 27.1929,
      "lng": 78.0308
    },
    {
      "id": "poi_udaipur_city-palace-udaipur",
      "cityId": "udaipur",
      "name": "City Palace Udaipur",
      "category": "Heritage",
      "description": "Rajasthan's largest palace, stacked above Lake Pichola.",
      "price": 300,
      "rating": 4.7,
      "imageUrl": null,
      "lat": 24.576,
      "lng": 73.6832
    },
    {
      "id": "poi_udaipur_lake-pichola-boat-ride",
      "cityId": "udaipur",
      "name": "Lake Pichola Boat Ride",
      "category": "Experience",
      "description": "Sunset shikara past Jag Mandir and the Lake Palace.",
      "price": 400,
      "rating": 4.8,
      "imageUrl": null,
      "lat": 24.5714,
      "lng": 73.68
    },
    {
      "id": "poi_udaipur_saheliyon-ki-bari",
      "cityId": "udaipur",
      "name": "Saheliyon ki Bari",
      "category": "Garden",
      "description": "Fountain garden built for the maids of honour.",
      "price": 100,
      "rating": 4.3,
      "imageUrl": null,
      "lat": 24.6017,
      "lng": 73.689
    },
    {
      "id": "poi_varanasi_dashashwamedh-ghat",
      "cityId": "varanasi",
      "name": "Dashashwamedh Ghat",
      "category": "Spiritual",
      "description": "The nightly Ganga Aarti with fire lamps and conches.",
      "price": 0,
      "rating": 4.8,
      "imageUrl": null,
      "lat": 25.3067,
      "lng": 83.0104
    },
    {
      "id": "poi_varanasi_sarnath",
      "cityId": "varanasi",
      "name": "Sarnath",
      "category": "Heritage",
      "description": "Where the Buddha gave his first sermon; Dhamek Stupa stands here.",
      "price": 300,
      "rating": 4.6,
      "imageUrl": null,
      "lat": 25.3811,
      "lng": 83.0244
    },
    {
      "id": "poi_varanasi_sunrise-boat-ride",
      "cityId": "varanasi",
      "name": "Sunrise Boat Ride",
      "category": "Experience",
      "description": "Row past 84 ghats as the city wakes.",
      "price": 500,
      "rating": 4.9,
      "imageUrl": null,
      "lat": 25.309,
      "lng": 83.0107
    },
    {
      "id": "poi_goa_basilica-of-bom-jesus",
      "cityId": "goa",
      "name": "Basilica of Bom Jesus",
      "category": "Heritage",
      "description": "Baroque church holding the relics of St Francis Xavier.",
      "price": 0,
      "rating": 4.6,
      "imageUrl": null,
      "lat": 15.5009,
      "lng": 73.9116
    },
    {
      "id": "poi_goa_palolem-beach",
      "cityId": "goa",
      "name": "Palolem Beach",
      "category": "Beach",
      "description": "Crescent bay of calm water and kayaks in the south.",
      "price": 0,
      "rating": 4.5,
      "imageUrl": null,
      "lat": 15.01,
      "lng": 74.0233
    },
    {
      "id": "poi_goa_dudhsagar-falls",
      "cityId": "goa",
      "name": "Dudhsagar Falls",
      "category": "Nature",
      "description": "Four-tier waterfall reached by jeep through the Bhagwan Mahavir sanctuary.",
      "price": 800,
      "rating": 4.6,
      "imageUrl": null,
      "lat": 15.3144,
      "lng": 74.3143
    },
    {
      "id": "poi_kerala_alleppey-backwaters",
      "cityId": "kerala",
      "name": "Alleppey Backwaters",
      "category": "Experience",
      "description": "Houseboat through paddy polders and coir villages.",
      "price": 6000,
      "rating": 4.8,
      "imageUrl": null,
      "lat": 9.4981,
      "lng": 76.3388
    },
    {
      "id": "poi_kerala_fort-kochi",
      "cityId": "kerala",
      "name": "Fort Kochi",
      "category": "Heritage",
      "description": "Chinese fishing nets, Dutch cemetery and Jew Town spice lanes.",
      "price": 0,
      "rating": 4.5,
      "imageUrl": null,
      "lat": 9.9658,
      "lng": 76.2422
    },
    {
      "id": "poi_kerala_munnar-tea-estates",
      "cityId": "kerala",
      "name": "Munnar Tea Estates",
      "category": "Nature",
      "description": "Rolling Kannan Devan hills at 1,600 m.",
      "price": 0,
      "rating": 4.7,
      "imageUrl": null,
      "lat": 10.0889,
      "lng": 77.0595
    },
    {
      "id": "poi_mumbai_gateway-of-india",
      "cityId": "mumbai",
      "name": "Gateway of India",
      "category": "Monument",
      "description": "The 1924 arch on the Apollo Bunder waterfront.",
      "price": 0,
      "rating": 4.5,
      "imageUrl": null,
      "lat": 18.922,
      "lng": 72.8347
    },
    {
      "id": "poi_mumbai_elephanta-caves",
      "cityId": "mumbai",
      "name": "Elephanta Caves",
      "category": "Heritage",
      "description": "Rock-cut Shiva cave temples on an island an hour offshore.",
      "price": 600,
      "rating": 4.5,
      "imageUrl": null,
      "lat": 18.9633,
      "lng": 72.9315
    },
    {
      "id": "poi_mumbai_marine-drive",
      "cityId": "mumbai",
      "name": "Marine Drive",
      "category": "Experience",
      "description": "The Queen's Necklace curve, best at dusk.",
      "price": 0,
      "rating": 4.7,
      "imageUrl": null,
      "lat": 18.9438,
      "lng": 72.823
    },
    {
      "id": "poi_kashmir_dal-lake-shikara",
      "cityId": "kashmir",
      "name": "Dal Lake Shikara",
      "category": "Experience",
      "description": "Floating gardens, houseboats and the Zabarwan backdrop.",
      "price": 800,
      "rating": 4.8,
      "imageUrl": null,
      "lat": 34.1183,
      "lng": 74.858
    },
    {
      "id": "poi_kashmir_gulmarg-gondola",
      "cityId": "kashmir",
      "name": "Gulmarg Gondola",
      "category": "Nature",
      "description": "One of the world's highest cable cars to 3,980 m.",
      "price": 1600,
      "rating": 4.7,
      "imageUrl": null,
      "lat": 34.0484,
      "lng": 74.3805
    },
    {
      "id": "poi_leh_pangong-tso",
      "cityId": "leh",
      "name": "Pangong Tso",
      "category": "Nature",
      "description": "Colour-shifting lake at 4,350 m on the Tibetan plateau.",
      "price": 0,
      "rating": 4.9,
      "imageUrl": null,
      "lat": 33.7554,
      "lng": 78.674
    },
    {
      "id": "poi_leh_thiksey-monastery",
      "cityId": "leh",
      "name": "Thiksey Monastery",
      "category": "Spiritual",
      "description": "Twelve-storey gompa with a 15 m Maitreya Buddha.",
      "price": 100,
      "rating": 4.7,
      "imageUrl": null,
      "lat": 34.0556,
      "lng": 77.6664
    },
    {
      "id": "poi_kolkata_victoria-memorial",
      "cityId": "kolkata",
      "name": "Victoria Memorial",
      "category": "Heritage",
      "description": "Marble monument to British India housing a sprawling colonial-era museum.",
      "price": 30,
      "rating": 4.6,
      "imageUrl": null,
      "lat": 22.5448,
      "lng": 88.3426
    },
    {
      "id": "poi_kolkata_howrah-bridge",
      "cityId": "kolkata",
      "name": "Howrah Bridge",
      "category": "Landmark",
      "description": "Cantilever bridge over the Hooghly — busiest of its kind in the world.",
      "price": 0,
      "rating": 4.5,
      "imageUrl": null,
      "lat": 22.5851,
      "lng": 88.3468
    },
    {
      "id": "poi_kolkata_dakshineswar-kali-temple",
      "cityId": "kolkata",
      "name": "Dakshineswar Kali Temple",
      "category": "Spiritual",
      "description": "Riverside temple linked to the mystic Ramakrishna Paramahansa.",
      "price": 0,
      "rating": 4.6,
      "imageUrl": null,
      "lat": 22.6547,
      "lng": 88.3576
    },
    {
      "id": "poi_kolkata_college-street",
      "cityId": "kolkata",
      "name": "College Street",
      "category": "Market",
      "description": "Asia's largest second-hand book market, running for over a kilometre.",
      "price": 0,
      "rating": 4.4,
      "imageUrl": null,
      "lat": 22.5744,
      "lng": 88.363
    },
    {
      "id": "poi_kolkata_indian-museum",
      "cityId": "kolkata",
      "name": "Indian Museum",
      "category": "Heritage",
      "description": "India's oldest and largest museum, since 1814.",
      "price": 50,
      "rating": 4.3,
      "imageUrl": null,
      "lat": 22.5579,
      "lng": 88.3512
    },
    {
      "id": "poi_chennai_kapaleeshwarar-temple",
      "cityId": "chennai",
      "name": "Kapaleeshwarar Temple",
      "category": "Spiritual",
      "description": "Dravidian-style temple with a towering painted gopuram in Mylapore.",
      "price": 0,
      "rating": 4.7,
      "imageUrl": null,
      "lat": 13.0336,
      "lng": 80.2699
    },
    {
      "id": "poi_chennai_marina-beach",
      "cityId": "chennai",
      "name": "Marina Beach",
      "category": "Beach",
      "description": "One of the world's longest urban beaches, busy at sunrise and sunset.",
      "price": 0,
      "rating": 4.4,
      "imageUrl": null,
      "lat": 13.05,
      "lng": 80.2824
    },
    {
      "id": "poi_chennai_fort-st-george",
      "cityId": "chennai",
      "name": "Fort St. George",
      "category": "Heritage",
      "description": "First English fortress in India, built in 1644.",
      "price": 30,
      "rating": 4.3,
      "imageUrl": null,
      "lat": 13.0797,
      "lng": 80.2874
    },
    {
      "id": "poi_chennai_mahabalipuram-shore-temple",
      "cityId": "chennai",
      "name": "Mahabalipuram Shore Temple",
      "category": "Heritage",
      "description": "UNESCO-listed 7th-century granite temple facing the Bay of Bengal.",
      "price": 40,
      "rating": 4.6,
      "imageUrl": null,
      "lat": 12.6169,
      "lng": 80.1994
    },
    {
      "id": "poi_mysuru_mysore-palace",
      "cityId": "mysuru",
      "name": "Mysore Palace",
      "category": "Heritage",
      "description": "Indo-Saracenic royal palace, lit with 100,000 bulbs on Sunday nights.",
      "price": 70,
      "rating": 4.8,
      "imageUrl": null,
      "lat": 12.3052,
      "lng": 76.6552
    },
    {
      "id": "poi_mysuru_chamundi-hill",
      "cityId": "mysuru",
      "name": "Chamundi Hill",
      "category": "Viewpoint",
      "description": "Hilltop temple and city panorama, reached by 1,000 stone steps or road.",
      "price": 0,
      "rating": 4.5,
      "imageUrl": null,
      "lat": 12.2753,
      "lng": 76.6703
    },
    {
      "id": "poi_mysuru_devaraja-market",
      "cityId": "mysuru",
      "name": "Devaraja Market",
      "category": "Market",
      "description": "Century-old market piled with flowers, spices and sandalwood.",
      "price": 0,
      "rating": 4.4,
      "imageUrl": null,
      "lat": 12.3088,
      "lng": 76.6515
    },
    {
      "id": "poi_pushkar_pushkar-lake",
      "cityId": "pushkar",
      "name": "Pushkar Lake",
      "category": "Spiritual",
      "description": "Holy lake ringed by 52 bathing ghats and 500 temples.",
      "price": 0,
      "rating": 4.6,
      "imageUrl": null,
      "lat": 26.4893,
      "lng": 74.5524
    },
    {
      "id": "poi_pushkar_brahma-temple",
      "cityId": "pushkar",
      "name": "Brahma Temple",
      "category": "Spiritual",
      "description": "One of the very few temples on earth dedicated to Brahma.",
      "price": 0,
      "rating": 4.5,
      "imageUrl": null,
      "lat": 26.4878,
      "lng": 74.5517
    },
    {
      "id": "poi_pushkar_savitri-temple-viewpoint",
      "cityId": "pushkar",
      "name": "Savitri Temple Viewpoint",
      "category": "Viewpoint",
      "description": "Ropeway or hilltop hike above the lake for sunset views.",
      "price": 100,
      "rating": 4.5,
      "imageUrl": null,
      "lat": 26.4856,
      "lng": 74.5361
    },
    {
      "id": "poi_ahmedabad_sabarmati-ashram",
      "cityId": "ahmedabad",
      "name": "Sabarmati Ashram",
      "category": "Heritage",
      "description": "Gandhi's riverside home and independence-movement headquarters.",
      "price": 0,
      "rating": 4.7,
      "imageUrl": null,
      "lat": 23.0605,
      "lng": 72.5801
    },
    {
      "id": "poi_ahmedabad_adalaj-stepwell",
      "cityId": "ahmedabad",
      "name": "Adalaj Stepwell",
      "category": "Heritage",
      "description": "Five-storey carved stepwell from 1499.",
      "price": 0,
      "rating": 4.6,
      "imageUrl": null,
      "lat": 23.1667,
      "lng": 72.58
    },
    {
      "id": "poi_ahmedabad_sidi-saiyyed-mosque",
      "cityId": "ahmedabad",
      "name": "Sidi Saiyyed Mosque",
      "category": "Heritage",
      "description": "Famous for its intricately carved stone jaali windows.",
      "price": 0,
      "rating": 4.5,
      "imageUrl": null,
      "lat": 23.028,
      "lng": 72.5815
    },
    {
      "id": "poi_ahmedabad_manek-chowk",
      "cityId": "ahmedabad",
      "name": "Manek Chowk",
      "category": "Market",
      "description": "Jewellery market by day, street-food night market after dark.",
      "price": 0,
      "rating": 4.5,
      "imageUrl": null,
      "lat": 23.0248,
      "lng": 72.5888
    }
  ],
  "restaurants": [
    {
      "id": "rest_jaipur_laxmi-misthan-bhandar-lmb",
      "cityId": "jaipur",
      "name": "Laxmi Misthan Bhandar (LMB)",
      "area": "Johari Bazaar",
      "description": "Iconic 1727 sweet shop and thali joint.",
      "mustTryDish": "Dal Baati Churma",
      "priceForTwo": 800,
      "lat": 26.95128888888889,
      "lng": 75.8373
    },
    {
      "id": "rest_jaipur_rawat-mishtan-bhandar",
      "cityId": "jaipur",
      "name": "Rawat Mishtan Bhandar",
      "area": "Station Road",
      "description": "Cash-only institution, always packed with locals.",
      "mustTryDish": "Pyaaz kachori",
      "priceForTwo": 400,
      "lat": 26.89795555555556,
      "lng": 75.7973
    },
    {
      "id": "rest_jaipur_suvarna-mahal",
      "cityId": "jaipur",
      "name": "Suvarna Mahal",
      "area": "Rambagh Palace",
      "description": "Royal Rajasthani in a maharaja's former dining hall.",
      "mustTryDish": "Laal maas",
      "priceForTwo": 7000,
      "lat": 26.935733333333335,
      "lng": 75.83952222222223
    },
    {
      "id": "rest_jaipur_handi-restaurant",
      "cityId": "jaipur",
      "name": "Handi Restaurant",
      "area": "MI Road",
      "description": "Smoky tandoor and handi meats since 1980.",
      "mustTryDish": "Handi mutton",
      "priceForTwo": 1400,
      "lat": 26.913511111111113,
      "lng": 75.79507777777778
    },
    {
      "id": "rest_delhi_karims",
      "cityId": "delhi",
      "name": "Karim's",
      "area": "Jama Masjid",
      "description": "Mughlai kitchen run by the same family since 1913.",
      "mustTryDish": "Mutton burra",
      "priceForTwo": 900,
      "lat": 28.607233333333333,
      "lng": 77.16233333333334
    },
    {
      "id": "rest_delhi_bukhara",
      "cityId": "delhi",
      "name": "Bukhara",
      "area": "ITC Maurya",
      "description": "North-West Frontier grills; a global top-100 fixture.",
      "mustTryDish": "Dal Bukhara",
      "priceForTwo": 8000,
      "lat": 28.638344444444446,
      "lng": 77.15788888888889
    },
    {
      "id": "rest_delhi_paranthe-wali-gali",
      "cityId": "delhi",
      "name": "Paranthe Wali Gali",
      "area": "Chandni Chowk",
      "description": "A lane of fried-paratha stalls, unchanged for a century.",
      "mustTryDish": "Rabri paratha",
      "priceForTwo": 300,
      "lat": 28.570566666666668,
      "lng": 77.239
    },
    {
      "id": "rest_delhi_indian-accent",
      "cityId": "delhi",
      "name": "Indian Accent",
      "area": "Lodhi Road",
      "description": "Modern Indian tasting menus, consistently India's #1.",
      "mustTryDish": "Daulat ki chaat",
      "priceForTwo": 12000,
      "lat": 28.65501111111111,
      "lng": 77.16344444444445
    },
    {
      "id": "rest_agra_pinch-of-spice",
      "cityId": "agra",
      "name": "Pinch of Spice",
      "area": "Fatehabad Road",
      "description": "Reliable upscale Mughlai — great after a long Taj morning.",
      "mustTryDish": "Mughlai thali",
      "priceForTwo": 1800,
      "lat": 27.137811111111112,
      "lng": 77.9581
    },
    {
      "id": "rest_agra_panchhi-petha-store",
      "cityId": "agra",
      "name": "Panchhi Petha Store",
      "area": "Sadar Bazaar",
      "description": "The original 100-year-old petha shop — Agra's iconic ash-gourd sweet.",
      "mustTryDish": "Kesar petha",
      "priceForTwo": 300,
      "lat": 27.227811111111112,
      "lng": 78.03254444444444
    },
    {
      "id": "rest_agra_esphahan-oberoi-amarvilas",
      "cityId": "agra",
      "name": "Esphahan (Oberoi Amarvilas)",
      "area": "Taj East Gate",
      "description": "Fine-dining Mughlai with a Taj view — the most romantic table in India.",
      "mustTryDish": "Awadhi tasting menu",
      "priceForTwo": 12000,
      "lat": 27.208922222222224,
      "lng": 78.01143333333333
    },
    {
      "id": "rest_agra_joneys-place",
      "cityId": "agra",
      "name": "Joney's Place",
      "area": "Taj Ganj",
      "description": "Traveler-favorite tiny cafe — everything under ₹200.",
      "mustTryDish": "Banana lassi",
      "priceForTwo": 400,
      "lat": 27.1967,
      "lng": 78.03698888888889
    },
    {
      "id": "rest_udaipur_ambrai",
      "cityId": "udaipur",
      "name": "Ambrai",
      "area": "Amet Haveli",
      "description": "Lakeside table facing the City Palace lit up at night.",
      "mustTryDish": "Laal maas",
      "priceForTwo": 3000,
      "lat": 24.62762222222222,
      "lng": 73.67472222222223
    },
    {
      "id": "rest_varanasi_kashi-chat-bhandar",
      "cityId": "varanasi",
      "name": "Kashi Chat Bhandar",
      "area": "Godowlia",
      "description": "Legendary tamatar chaat and palak patta chaat.",
      "mustTryDish": "Tamatar chaat",
      "priceForTwo": 250,
      "lat": 25.2976,
      "lng": 82.94501111111111
    },
    {
      "id": "rest_mumbai_britannia-co",
      "cityId": "mumbai",
      "name": "Britannia & Co.",
      "area": "Ballard Estate",
      "description": "Parsi cafe from 1923 with a famous berry pulao.",
      "mustTryDish": "Berry pulao",
      "priceForTwo": 1400,
      "lat": 19.02711111111111,
      "lng": 72.86881111111111
    },
    {
      "id": "rest_kolkata_peter-cat",
      "cityId": "kolkata",
      "name": "Peter Cat",
      "area": "Park Street",
      "description": "Old-school Kolkata institution behind the sizzling Chelo Kebab.",
      "mustTryDish": "Chelo Kebab",
      "priceForTwo": 900,
      "lat": 22.577044444444446,
      "lng": 88.39501111111112
    },
    {
      "id": "rest_chennai_murugan-idli-shop",
      "cityId": "chennai",
      "name": "Murugan Idli Shop",
      "area": "T. Nagar",
      "description": "Soft idlis and podi idlis served on banana leaf since 1978.",
      "mustTryDish": "Podi Idli",
      "priceForTwo": 400,
      "lat": 13.066033333333333,
      "lng": 80.26514444444445
    },
    {
      "id": "rest_mysuru_vinayaka-mylari",
      "cityId": "mysuru",
      "name": "Vinayaka Mylari",
      "area": "Nazarbad",
      "description": "The dosa that gave Mysore masala dosa its name — thin, buttery, unique red chutney.",
      "mustTryDish": "Mysore Masala Dosa",
      "priceForTwo": 250,
      "lat": 12.333577777777778,
      "lng": 76.68162222222222
    },
    {
      "id": "rest_pushkar_sixth-sense-rooftop",
      "cityId": "pushkar",
      "name": "Sixth Sense Rooftop",
      "area": "Near Brahma Temple",
      "description": "Rooftop cafe overlooking the lake and ghats.",
      "mustTryDish": "Rajasthani Thali",
      "priceForTwo": 500,
      "lat": 26.542122222222222,
      "lng": 74.58332222222222
    },
    {
      "id": "rest_ahmedabad_agashiye",
      "cityId": "ahmedabad",
      "name": "Agashiye",
      "area": "Old City",
      "description": "Rooftop heritage haveli serving a traditional unlimited Gujarati thali.",
      "mustTryDish": "Gujarati Thali",
      "priceForTwo": 1200,
      "lat": 23.0125,
      "lng": 72.6125111111111
    },
    {
      "id": "rest_goa_gunpowder",
      "cityId": "goa",
      "name": "Gunpowder",
      "area": "Assagao",
      "description": "South Indian coastal cooking in a garden shack.",
      "mustTryDish": "Kerala fish curry",
      "priceForTwo": 2000,
      "lat": 15.271522222222222,
      "lng": 74.15177777777777
    },
    {
      "id": "rest_kerala_kayees-rahmathulla",
      "cityId": "kerala",
      "name": "Kayees Rahmathulla",
      "area": "Mattancherry",
      "description": "Biryani counter Anthony Bourdain queued at.",
      "mustTryDish": "Mutton biryani",
      "priceForTwo": 500,
      "lat": 9.488100000000001,
      "lng": 76.37991111111111
    },
    {
      "id": "rest_hyderabad_paradise",
      "cityId": "hyderabad",
      "name": "Paradise",
      "area": "Secunderabad",
      "description": "The benchmark Hyderabadi dum biryani since 1953.",
      "mustTryDish": "Mutton dum biryani",
      "priceForTwo": 900,
      "lat": 17.395000000000003,
      "lng": 78.44558888888889
    },
    {
      "id": "rest_bangkok_jay-fai",
      "cityId": "bangkok",
      "name": "Jay Fai",
      "area": "Phra Nakhon",
      "description": "Michelin-starred street wok cooked over charcoal.",
      "mustTryDish": "Crab omelette",
      "priceForTwo": 4000,
      "lat": 13.785188888888888,
      "lng": 100.4818
    }
  ],
  "stays": [
    {
      "id": "stay_jaipur_zostel-jaipur",
      "cityId": "jaipur",
      "name": "Zostel Jaipur",
      "priceTier": "budget",
      "type": "Hostel",
      "area": "Bani Park",
      "pricePerNight": 700,
      "distanceFromCenterKm": 4.9,
      "imageUrl": null,
      "lat": 26.90351111111111,
      "lng": 75.83618888888888
    },
    {
      "id": "stay_jaipur_hotel-pearl-palace",
      "cityId": "jaipur",
      "name": "Hotel Pearl Palace",
      "priceTier": "mid",
      "type": "Boutique",
      "area": "Hathroi Fort",
      "pricePerNight": 3500,
      "distanceFromCenterKm": 3.1,
      "imageUrl": null,
      "lat": 26.916844444444447,
      "lng": 75.81841111111112
    },
    {
      "id": "stay_jaipur_rambagh-palace",
      "cityId": "jaipur",
      "name": "Rambagh Palace",
      "priceTier": "luxury",
      "type": "Heritage Palace",
      "area": "Bhawani Singh Rd",
      "pricePerNight": 45000,
      "distanceFromCenterKm": 2.4,
      "imageUrl": null,
      "lat": 26.894622222222225,
      "lng": 75.77396666666667
    },
    {
      "id": "stay_delhi_madpackers-hostel",
      "cityId": "delhi",
      "name": "Madpackers Hostel",
      "priceTier": "budget",
      "type": "Hostel",
      "area": "Hauz Khas",
      "pricePerNight": 900,
      "distanceFromCenterKm": 3.1,
      "imageUrl": null,
      "lat": 28.618344444444446,
      "lng": 77.24011111111112
    },
    {
      "id": "stay_delhi_bloomrooms-new-delhi",
      "cityId": "delhi",
      "name": "Bloomrooms @ New Delhi",
      "priceTier": "mid",
      "type": "Boutique",
      "area": "Paharganj",
      "pricePerNight": 3800,
      "distanceFromCenterKm": 5.6,
      "imageUrl": null,
      "lat": 28.657233333333334,
      "lng": 77.179
    },
    {
      "id": "stay_delhi_the-imperial",
      "cityId": "delhi",
      "name": "The Imperial",
      "priceTier": "luxury",
      "type": "Heritage",
      "area": "Janpath",
      "pricePerNight": 32000,
      "distanceFromCenterKm": 0,
      "imageUrl": null,
      "lat": 28.6139,
      "lng": 77.209
    },
    {
      "id": "stay_agra_joeys-hostel",
      "cityId": "agra",
      "name": "Joey's Hostel",
      "priceTier": "budget",
      "type": "Hostel",
      "area": "Taj Ganj",
      "pricePerNight": 650,
      "distanceFromCenterKm": 6.9,
      "imageUrl": null,
      "lat": 27.2167,
      "lng": 77.95476666666667
    },
    {
      "id": "stay_agra_hotel-taj-resorts",
      "cityId": "agra",
      "name": "Hotel Taj Resorts",
      "priceTier": "mid",
      "type": "Hotel",
      "area": "Taj South Gate",
      "pricePerNight": 3200,
      "distanceFromCenterKm": 5.4,
      "imageUrl": null,
      "lat": 27.16892222222222,
      "lng": 77.95365555555556
    },
    {
      "id": "stay_agra_oberoi-amarvilas",
      "cityId": "agra",
      "name": "Oberoi Amarvilas",
      "priceTier": "luxury",
      "type": "Resort",
      "area": "Taj East Gate",
      "pricePerNight": 70000,
      "distanceFromCenterKm": 5.7,
      "imageUrl": null,
      "lat": 27.152255555555556,
      "lng": 78.05921111111111
    },
    {
      "id": "stay_udaipur_bunkyard-hostel",
      "cityId": "udaipur",
      "name": "Bunkyard Hostel",
      "priceTier": "budget",
      "type": "Hostel",
      "area": "Hanuman Ghat",
      "pricePerNight": 800,
      "distanceFromCenterKm": 5.4,
      "imageUrl": null,
      "lat": 24.548733333333335,
      "lng": 73.67805555555556
    },
    {
      "id": "stay_udaipur_jagat-niwas-palace",
      "cityId": "udaipur",
      "name": "Jagat Niwas Palace",
      "priceTier": "mid",
      "type": "Haveli",
      "area": "Lal Ghat",
      "pricePerNight": 6000,
      "distanceFromCenterKm": 5.3,
      "imageUrl": null,
      "lat": 24.537622222222222,
      "lng": 73.71138888888889
    },
    {
      "id": "stay_udaipur_taj-lake-palace",
      "cityId": "udaipur",
      "name": "Taj Lake Palace",
      "priceTier": "luxury",
      "type": "Island Palace",
      "area": "Lake Pichola",
      "pricePerNight": 85000,
      "distanceFromCenterKm": 2.4,
      "imageUrl": null,
      "lat": 24.567622222222223,
      "lng": 73.69916666666667
    },
    {
      "id": "stay_goa_the-hosteller",
      "cityId": "goa",
      "name": "The Hosteller",
      "priceTier": "budget",
      "type": "Hostel",
      "area": "Anjuna",
      "pricePerNight": 800,
      "distanceFromCenterKm": 5.3,
      "imageUrl": null,
      "lat": 15.251522222222222,
      "lng": 74.12288888888888
    },
    {
      "id": "stay_goa_coconut-creek",
      "cityId": "goa",
      "name": "Coconut Creek",
      "priceTier": "mid",
      "type": "Resort",
      "area": "Bogmalo",
      "pricePerNight": 6500,
      "distanceFromCenterKm": 6.7,
      "imageUrl": null,
      "lat": 15.25818888888889,
      "lng": 74.16955555555555
    },
    {
      "id": "stay_kerala_zostel-alleppey",
      "cityId": "kerala",
      "name": "Zostel Alleppey",
      "priceTier": "budget",
      "type": "Hostel",
      "area": "Alleppey",
      "pricePerNight": 750,
      "distanceFromCenterKm": 0.9,
      "imageUrl": null,
      "lat": 9.499211111111112,
      "lng": 76.34657777777778
    },
    {
      "id": "stay_kerala_xandari-riverscapes",
      "cityId": "kerala",
      "name": "Xandari Riverscapes",
      "priceTier": "mid",
      "type": "Houseboat",
      "area": "Backwaters",
      "pricePerNight": 9000,
      "distanceFromCenterKm": 2.4,
      "imageUrl": null,
      "lat": 9.511433333333335,
      "lng": 76.32102222222223
    }
  ],
  "transportOptions": [
    {
      "id": "trans_jaipur_auto-rickshaw",
      "cityId": "jaipur",
      "mode": "Auto-rickshaw",
      "costRange": "₹50–150 per hop",
      "timeEstimate": "10–25 min",
      "note": "Agree the fare before starting; meters are rare.",
      "costRankInr": 50,
      "timeRankMinutes": 10
    },
    {
      "id": "trans_jaipur_app-cab-uber-ola",
      "cityId": "jaipur",
      "mode": "App cab (Uber/Ola)",
      "costRange": "₹120–400",
      "timeEstimate": "15–30 min",
      "note": "Cheapest reliable option for Amber Fort and back.",
      "costRankInr": 120,
      "timeRankMinutes": 15
    },
    {
      "id": "trans_jaipur_full-day-taxi",
      "cityId": "jaipur",
      "mode": "Full-day taxi",
      "costRange": "₹1,800–2,500/day",
      "timeEstimate": "8 hours",
      "note": "Best value if you're doing Amber + Nahargarh + city in one day.",
      "costRankInr": 1800,
      "timeRankMinutes": 480
    },
    {
      "id": "trans_jaipur_metro-pink-line",
      "cityId": "jaipur",
      "mode": "Metro (Pink Line)",
      "costRange": "₹6–20",
      "timeEstimate": "5–15 min",
      "note": "Only useful along Mansarovar–Chandpole.",
      "costRankInr": 6,
      "timeRankMinutes": 5
    },
    {
      "id": "trans_delhi_delhi-metro",
      "cityId": "delhi",
      "mode": "Delhi Metro",
      "costRange": "₹10–60",
      "timeEstimate": "15–45 min",
      "note": "Fastest way across the city; avoid 9–10am and 6–8pm.",
      "costRankInr": 10,
      "timeRankMinutes": 15
    },
    {
      "id": "trans_delhi_auto-rickshaw",
      "cityId": "delhi",
      "mode": "Auto-rickshaw",
      "costRange": "₹40–200",
      "timeEstimate": "10–30 min",
      "note": "Insist on the meter or use the app.",
      "costRankInr": 40,
      "timeRankMinutes": 10
    },
    {
      "id": "trans_delhi_app-cab",
      "cityId": "delhi",
      "mode": "App cab",
      "costRange": "₹150–600",
      "timeEstimate": "20–50 min",
      "note": "Traffic-dependent; metro usually wins mid-day.",
      "costRankInr": 150,
      "timeRankMinutes": 20
    },
    {
      "id": "trans_delhi_airport-express",
      "cityId": "delhi",
      "mode": "Airport Express",
      "costRange": "₹60",
      "timeEstimate": "20 min",
      "note": "New Delhi station to T3 in twenty minutes flat.",
      "costRankInr": 60,
      "timeRankMinutes": 20
    },
    {
      "id": "trans_agra_battery-bus-e-rickshaw",
      "cityId": "agra",
      "mode": "Battery bus / e-rickshaw",
      "costRange": "₹10–50",
      "timeEstimate": "5–15 min",
      "note": "Mandatory for the last 500 m to the Taj gates.",
      "costRankInr": 10,
      "timeRankMinutes": 5
    },
    {
      "id": "trans_agra_gatimaan-express-from-delhi",
      "cityId": "agra",
      "mode": "Gatimaan Express (from Delhi)",
      "costRange": "₹800–1,600",
      "timeEstimate": "100 min",
      "note": "India's fastest train; ideal for a day trip.",
      "costRankInr": 800,
      "timeRankMinutes": 100
    },
    {
      "id": "trans_agra_full-day-taxi",
      "cityId": "agra",
      "mode": "Full-day taxi",
      "costRange": "₹2,000",
      "timeEstimate": "8 hours",
      "note": "Covers Taj, Fort and Fatehpur Sikri comfortably.",
      "costRankInr": 2000,
      "timeRankMinutes": 480
    },
    {
      "id": "trans_udaipur_auto-rickshaw",
      "cityId": "udaipur",
      "mode": "Auto-rickshaw",
      "costRange": "₹60–200",
      "timeEstimate": "10–20 min",
      "note": "Old city lanes are walkable — use autos for Sajjangarh.",
      "costRankInr": 60,
      "timeRankMinutes": 10
    },
    {
      "id": "trans_goa_scooter-rental",
      "cityId": "goa",
      "mode": "Scooter rental",
      "costRange": "₹400–600/day",
      "timeEstimate": "anywhere",
      "note": "The only sensible way to move; carry your licence.",
      "costRankInr": 400,
      "timeRankMinutes": 999
    },
    {
      "id": "trans_kerala_ferry-kochi",
      "cityId": "kerala",
      "mode": "Ferry (Kochi)",
      "costRange": "₹4–40",
      "timeEstimate": "20–30 min",
      "note": "Fort Kochi to Ernakulam beats the road every time.",
      "costRankInr": 4,
      "timeRankMinutes": 20
    },
    {
      "id": "trans_kolkata_kolkata-metro",
      "cityId": "kolkata",
      "mode": "Kolkata Metro",
      "costRange": "₹5-30",
      "timeEstimate": "15-40 min",
      "note": "Fast, cheap way across the city, avoids traffic.",
      "costRankInr": 5,
      "timeRankMinutes": 15
    },
    {
      "id": "trans_kolkata_yellow-taxi",
      "cityId": "kolkata",
      "mode": "Yellow Taxi",
      "costRange": "₹100-300",
      "timeEstimate": "20-45 min",
      "note": "Iconic Ambassador cabs, agree on fare or ask for the meter.",
      "costRankInr": 100,
      "timeRankMinutes": 20
    },
    {
      "id": "trans_chennai_chennai-metro",
      "cityId": "chennai",
      "mode": "Chennai Metro",
      "costRange": "₹10-60",
      "timeEstimate": "15-40 min",
      "note": "Covers most major sights along the Blue and Green lines.",
      "costRankInr": 10,
      "timeRankMinutes": 15
    },
    {
      "id": "trans_chennai_app-cab",
      "cityId": "chennai",
      "mode": "App cab",
      "costRange": "₹150-450",
      "timeEstimate": "15-40 min",
      "note": "Most reliable for Mahabalipuram day trips.",
      "costRankInr": 150,
      "timeRankMinutes": 15
    },
    {
      "id": "trans_mysuru_app-cab",
      "cityId": "mysuru",
      "mode": "App cab",
      "costRange": "₹100-350",
      "timeEstimate": "10-30 min",
      "note": "Cheapest reliable option around the city.",
      "costRankInr": 100,
      "timeRankMinutes": 10
    },
    {
      "id": "trans_pushkar_cycle-rental",
      "cityId": "pushkar",
      "mode": "Cycle rental",
      "costRange": "₹100-200/day",
      "timeEstimate": "flexible",
      "note": "The whole town is walkable/cyclable, no need for cabs.",
      "costRankInr": 100,
      "timeRankMinutes": 999
    },
    {
      "id": "trans_ahmedabad_janmarg-brts",
      "cityId": "ahmedabad",
      "mode": "Janmarg BRTS",
      "costRange": "₹10-30",
      "timeEstimate": "15-40 min",
      "note": "Dedicated bus corridor covering most tourist stops.",
      "costRankInr": 10,
      "timeRankMinutes": 15
    }
  ],
  "markets": [
    {
      "id": "market_jaipur_johari-bazaar",
      "cityId": "jaipur",
      "name": "Johari Bazaar",
      "specialty": "Gems & Traditional Jewellery",
      "description": "Best for Kundan, meenakari and loose stones.",
      "hagglingExpected": true,
      "imageUrl": null
    },
    {
      "id": "market_jaipur_bapu-bazaar",
      "cityId": "jaipur",
      "name": "Bapu Bazaar",
      "specialty": "Textiles & Juttis",
      "description": "Best for Block prints, mojris and razai quilts.",
      "hagglingExpected": true,
      "imageUrl": null
    },
    {
      "id": "market_jaipur_tripolia-bazaar",
      "cityId": "jaipur",
      "name": "Tripolia Bazaar",
      "specialty": "Lac Bangles & Ironware",
      "description": "Best for Lakh bangles made while you wait.",
      "hagglingExpected": true,
      "imageUrl": null
    },
    {
      "id": "market_delhi_chandni-chowk",
      "cityId": "delhi",
      "name": "Chandni Chowk",
      "specialty": "Wedding Wear & Spices",
      "description": "Best for Silk sarees, silver jewelry, Indian sweets.",
      "hagglingExpected": true,
      "imageUrl": null
    },
    {
      "id": "market_delhi_dilli-haat-ina",
      "cityId": "delhi",
      "name": "Dilli Haat (INA)",
      "specialty": "Pan-India Crafts",
      "description": "Best for State-wise handicrafts under one roof.",
      "hagglingExpected": true,
      "imageUrl": null
    },
    {
      "id": "market_delhi_sarojini-nagar",
      "cityId": "delhi",
      "name": "Sarojini Nagar",
      "specialty": "Export-Surplus Fashion",
      "description": "Best for Branded seconds at throwaway prices.",
      "hagglingExpected": true,
      "imageUrl": null
    },
    {
      "id": "market_agra_sadar-bazaar",
      "cityId": "agra",
      "name": "Sadar Bazaar",
      "specialty": "Leather & Petha",
      "description": "Best for Shoes, bags and boxes of kesar petha.",
      "hagglingExpected": true,
      "imageUrl": null
    },
    {
      "id": "market_agra_kinari-bazaar",
      "cityId": "agra",
      "name": "Kinari Bazaar",
      "specialty": "Marble Inlay",
      "description": "Best for Pietra dura coasters and tabletops.",
      "hagglingExpected": true,
      "imageUrl": null
    },
    {
      "id": "market_udaipur_hathi-pol-bazaar",
      "cityId": "udaipur",
      "name": "Hathi Pol Bazaar",
      "specialty": "Miniature Painting",
      "description": "Best for Mewar-school art on silk and paper.",
      "hagglingExpected": true,
      "imageUrl": null
    },
    {
      "id": "market_varanasi_vishwanath-gali",
      "cityId": "varanasi",
      "name": "Vishwanath Gali",
      "specialty": "Banarasi Silk",
      "description": "Best for Handloom saris and brocade.",
      "hagglingExpected": true,
      "imageUrl": null
    },
    {
      "id": "market_goa_anjuna-flea-market",
      "cityId": "goa",
      "name": "Anjuna Flea Market",
      "specialty": "Boho & Beachwear",
      "description": "Best for Wednesdays only; bargain hard.",
      "hagglingExpected": true,
      "imageUrl": null
    },
    {
      "id": "market_kerala_jew-town-mattancherry",
      "cityId": "kerala",
      "name": "Jew Town, Mattancherry",
      "specialty": "Spices & Antiques",
      "description": "Best for Cardamom, pepper and colonial furniture.",
      "hagglingExpected": true,
      "imageUrl": null
    }
  ],
  "staticContent": [
    {
      "id": "privacyPolicy",
      "title": "Privacy Policy",
      "body": "## What we collect\n\nYour name, email address and the trips, templates and chat messages you create in WanderWise. We do not collect payment data.\n\n## How we use it\n\nTo generate and store your itineraries, personalise recommendations, and answer your Local Guide questions. We do not sell your data or use it for advertising.\n\n## Third parties\n\nItinerary generation and the AI Local Guide are powered by the Claude API (Anthropic). Trip content you submit is sent to that service to produce a response. Authentication, database and file storage run on Google Firebase.\n\n## Your rights\n\nYou can edit your name, delete individual trips, and permanently delete your account and all associated data from the Profile screen at any time.\n\n## Security\n\nData is encrypted in transit and at rest. Access is restricted to your authenticated account through Firebase security rules and App Check.\n\n## Contact\n\nprivacy@wanderwise.app"
    },
    {
      "id": "termsOfService",
      "title": "Terms of Service",
      "body": "## The service\n\nWanderWise provides AI-assisted travel itineraries, curated tour suggestions and destination guidance. It is a planning aid, not a travel agency.\n\n## Accuracy\n\nPrices, opening hours, ratings and travel times are estimates that change frequently. Always confirm with the venue or operator.\n\n## Acceptable use\n\nOne account per person. Do not scrape, resell or automate access to the service.\n\n## AI-generated content\n\nItineraries and chat answers are machine-generated and may contain errors. Verify anything safety- or money-critical.\n\n## Liability\n\nWanderWise is provided \"as is\". We are not liable for losses arising from travel decisions made using the app."
    },
    {
      "id": "contactSupport",
      "title": "Contact Support",
      "body": "## Email support\n\nhelp@wanderwise.app — we reply within one business day.\n\n## In-app\n\nUse the Local Guide chat for destination questions; use email for account or bug reports.\n\n## Emergency numbers (India)\n\nUnified emergency helpline: 112 · Police: 100 · Ambulance: 108 · Tourist helpline: 1363 (toll-free, multilingual, 24×7).\n\n## Lost documents abroad\n\nContact your nearest embassy or consulate first, then file a local police report — most insurers require both."
    }
  ]
};
